### ISSUE TITLE
How do I run a query?

### ISSUE THREAD

**Issue by claudiordgz** [calexander3/rethinkdbexplorer-vscode#1]
This is great, I don't have to spend time setting up dependencies when running random queries. But I haven't been able to run it.

After setting up my connection settings on my json config

```
    "rethinkdbExplorer.host": "localhost",
    "rethinkdbExplorer.port": 29025,
    "rethinkdbExplorer.database": "something",
    "rethinkdbExplorer.username": "theTopDogUser",
    "rethinkdbExplorer.password": "AVeryApproppriateAndLongAndExhaustingPassword01",
    "rethinkdbExplorer.tls": false
```

How do I run a query after pasting it on the new file?

`r.tableList()`

I tried `cmd` + `alt` + `p` and `rethinkdb but I don't get a choice to run that

![image](https://user-images.githubusercontent.com/779325/55733435-d52a0c00-59eb-11e9-9069-7492afc9aec8.png)

Cheers!
Claudio

**Comment by calexander3** [comment]
@claudiordgz Two way: One is ctrl+shift+r or cmd+shift+r for mac. The second is a small button in the status bar - 
![statusbar](https://user-images.githubusercontent.com/1903766/55923842-5a244980-5bd5-11e9-971a-f36d8ec48dfb.png)

**Comment by claudiordgz** [comment]
thank you @calexander3!
